/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.ImageIcon;

/**
 *
 * @author Ivan
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public static void setField(String color, String coord) {
        ImageIcon icon = new ImageIcon(color);
        switch(coord) {     
            case "00" :
                MainGUI.label_00.setIcon(icon);
                break;
                
            case "01" :
                MainGUI.label_01.setIcon(icon);
                break;
            
            case "02" :
                MainGUI.label_02.setIcon(icon);
                break;
                
            case "03" :
                MainGUI.label_03.setIcon(icon);
                break;
                
            case "04" :
                MainGUI.label_04.setIcon(icon);
                break;
                
            case "05" :
                MainGUI.label_05.setIcon(icon);
                break;
                
            case "06" :
                MainGUI.label_06.setIcon(icon);
                break;
                
            case "10" :
                MainGUI.label_10.setIcon(icon);
                break;  
                
            case "11" :
                MainGUI.label_11.setIcon(icon);
                break;
                
            case "12" :
                MainGUI.label_12.setIcon(icon);
                break;
                
            case "13" :
                MainGUI.label_13.setIcon(icon);
                break;
                
            case "14" :
                MainGUI.label_14.setIcon(icon);
                break;
                
            case "15" :
                MainGUI.label_15.setIcon(icon);
                break;
                
            case "16" :
                MainGUI.label_16.setIcon(icon);
                break;   
                
            case "20" :
                MainGUI.label_20.setIcon(icon);
                break;  
                
            case "21" :
                MainGUI.label_21.setIcon(icon);
                break;
                
            case "22" :
                MainGUI.label_22.setIcon(icon);
                break;
                
            case "23" :
                MainGUI.label_23.setIcon(icon);
                break;
                
            case "24" :
                MainGUI.label_24.setIcon(icon);
                break;
                
            case "25" :
                MainGUI.label_25.setIcon(icon);
                break;
                
            case "26" :
                MainGUI.label_26.setIcon(icon);
                break;    
                
            case "30" :
                MainGUI.label_30.setIcon(icon);
                break;  
                
            case "31" :
                MainGUI.label_31.setIcon(icon);
                break;
                
            case "32" :
                MainGUI.label_32.setIcon(icon);
                break;
                
            case "33" :
                MainGUI.label_33.setIcon(icon);
                break;
                
            case "34" :
                MainGUI.label_34.setIcon(icon);
                break;
                
            case "35" :
                MainGUI.label_35.setIcon(icon);
                break;
                
            case "36" :
                MainGUI.label_36.setIcon(icon);
                break;  
                
            case "40" :
                MainGUI.label_40.setIcon(icon);
                break;  
                
            case "41" :
                MainGUI.label_41.setIcon(icon);
                break;
                
            case "42" :
                MainGUI.label_42.setIcon(icon);
                break;
                
            case "43" :
                MainGUI.label_43.setIcon(icon);
                break;
                
            case "44" :
                MainGUI.label_44.setIcon(icon);
                break;
                
            case "45" :
                MainGUI.label_45.setIcon(icon);
                break;
                
            case "46" :
                MainGUI.label_46.setIcon(icon);
                break; 
                
            case "50" :
                MainGUI.label_50.setIcon(icon);
                break;  
                
            case "51" :
                MainGUI.label_51.setIcon(icon);
                break;
                
            case "52" :
                MainGUI.label_52.setIcon(icon);
                break;
                
            case "53" :
                MainGUI.label_53.setIcon(icon);
                break;
                
            case "54" :
                MainGUI.label_54.setIcon(icon);
                break;
                
            case "55" :
                MainGUI.label_55.setIcon(icon);
                break;
                
            case "56" :
                MainGUI.label_56.setIcon(icon);
                System.out.println("im case: 56");
                break;   
                
            default : System.out.println("nichts wurde gesetzt");    
        }
        System.out.println("Feld:"+coord);
        System.out.println("Farbe:" + color);
    }
    
    public static void setMyNick(String nick) {
        label_my_nick.setForeground(Color.ORANGE);
        label_my_nick.setText(nick);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_01 = new javax.swing.JLabel();
        label_04 = new javax.swing.JLabel();
        label_05 = new javax.swing.JLabel();
        label_02 = new javax.swing.JLabel();
        label_06 = new javax.swing.JLabel();
        icon_blue = new javax.swing.JLabel();
        label_00 = new javax.swing.JLabel();
        label_player1 = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        label_10 = new javax.swing.JLabel();
        label_12 = new javax.swing.JLabel();
        label_player2 = new javax.swing.JLabel();
        label_13 = new javax.swing.JLabel();
        label_15 = new javax.swing.JLabel();
        label_16 = new javax.swing.JLabel();
        label_20 = new javax.swing.JLabel();
        label_21 = new javax.swing.JLabel();
        label_22 = new javax.swing.JLabel();
        label_14 = new javax.swing.JLabel();
        label_23 = new javax.swing.JLabel();
        label_24 = new javax.swing.JLabel();
        label_26 = new javax.swing.JLabel();
        label_25 = new javax.swing.JLabel();
        icon_red = new javax.swing.JLabel();
        label_30 = new javax.swing.JLabel();
        label_31 = new javax.swing.JLabel();
        label_32 = new javax.swing.JLabel();
        label_34 = new javax.swing.JLabel();
        label_33 = new javax.swing.JLabel();
        label_35 = new javax.swing.JLabel();
        label_36 = new javax.swing.JLabel();
        label_41 = new javax.swing.JLabel();
        label_40 = new javax.swing.JLabel();
        label_42 = new javax.swing.JLabel();
        label_44 = new javax.swing.JLabel();
        label_43 = new javax.swing.JLabel();
        label_46 = new javax.swing.JLabel();
        label_50 = new javax.swing.JLabel();
        label_51 = new javax.swing.JLabel();
        label_52 = new javax.swing.JLabel();
        label_53 = new javax.swing.JLabel();
        label_45 = new javax.swing.JLabel();
        label_55 = new javax.swing.JLabel();
        label_56 = new javax.swing.JLabel();
        label_player1_ist_dran = new javax.swing.JLabel();
        label_player2_ist_dran = new javax.swing.JLabel();
        button_column_5 = new javax.swing.JButton();
        button_column_4 = new javax.swing.JButton();
        button_column_3 = new javax.swing.JButton();
        label_03 = new javax.swing.JLabel();
        button_column_2 = new javax.swing.JButton();
        button_column_1 = new javax.swing.JButton();
        label_my_nick = new javax.swing.JLabel();
        button_column_0 = new javax.swing.JButton();
        label_54 = new javax.swing.JLabel();
        button_column_6 = new javax.swing.JButton();
        label_11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_chat = new javax.swing.JTextArea();
        tf_chat = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_connect = new javax.swing.JMenu();
        menuItem_connect = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setBounds(new java.awt.Rectangle(10, 10, 830, 524));

        label_01.setPreferredSize(new java.awt.Dimension(52, 51));

        label_04.setPreferredSize(new java.awt.Dimension(52, 51));

        label_05.setPreferredSize(new java.awt.Dimension(52, 51));

        label_02.setPreferredSize(new java.awt.Dimension(52, 51));

        label_06.setPreferredSize(new java.awt.Dimension(52, 51));

        icon_blue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/blau.png"))); // NOI18N

        label_00.setPreferredSize(new java.awt.Dimension(52, 51));

        label_player1.setText("Player 1");

        label_status.setForeground(new java.awt.Color(255, 0, 51));
        label_status.setText("unconnected");

        label_10.setPreferredSize(new java.awt.Dimension(52, 51));

        label_12.setPreferredSize(new java.awt.Dimension(52, 51));

        label_player2.setText("Player 2");

        label_13.setPreferredSize(new java.awt.Dimension(52, 51));

        label_15.setPreferredSize(new java.awt.Dimension(52, 51));

        label_14.setPreferredSize(new java.awt.Dimension(52, 51));

        icon_red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/rot.png"))); // NOI18N

        label_56.setPreferredSize(new java.awt.Dimension(52, 51));

        label_player1_ist_dran.setText("                ");

        label_player2_ist_dran.setText("                ");

        button_column_5.setText("^");
        button_column_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_column_5ActionPerformed(evt);
            }
        });

        button_column_4.setText("^");
        button_column_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_column_4ActionPerformed(evt);
            }
        });

        button_column_3.setText("^");
        button_column_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_column_3ActionPerformed(evt);
            }
        });

        button_column_2.setText("^");
        button_column_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_column_2ActionPerformed(evt);
            }
        });

        button_column_1.setText("^");
        button_column_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_column_1ActionPerformed(evt);
            }
        });

        button_column_0.setText("^");
        button_column_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_column_0ActionPerformed(evt);
            }
        });

        button_column_6.setText("^");
        button_column_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_column_6ActionPerformed(evt);
            }
        });

        label_11.setMaximumSize(new java.awt.Dimension(52, 51));
        label_11.setMinimumSize(new java.awt.Dimension(52, 51));
        label_11.setPreferredSize(new java.awt.Dimension(52, 51));

        ta_chat.setEditable(false);
        ta_chat.setColumns(20);
        ta_chat.setForeground(new java.awt.Color(153, 153, 153));
        ta_chat.setRows(5);
        jScrollPane1.setViewportView(ta_chat);

        tf_chat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_chatKeyPressed(evt);
            }
        });

        jButton8.setText("senden");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel2.setText("Chat:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/spielfeld.png"))); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menu_connect.setText("Connect");

        menuItem_connect.setText("connect");
        menuItem_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_connectActionPerformed(evt);
            }
        });
        menu_connect.add(menuItem_connect);

        jMenuItem2.setText("disconnect");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_connect.add(jMenuItem2);

        jMenuBar1.add(menu_connect);

        jMenu2.setText("Favourites");

        jMenuItem1.setText("join");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(label_41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(label_52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(button_column_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(label_36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(button_column_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(label_44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(672, 672, 672)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(label_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(label_53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(label_42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(button_column_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(label_player2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(label_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(jButton8))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(label_33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(770, 770, 770)
                .addComponent(label_player2_ist_dran, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(label_23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(label_15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(button_column_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(label_51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(label_player1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(label_34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(770, 770, 770)
                .addComponent(label_player1_ist_dran, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(label_13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(label_35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(label_my_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(label_16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(label_32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(label_status, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(label_45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(label_46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(label_03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(label_55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(label_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(button_column_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(612, 612, 612)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(label_43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(label_12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(label_54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(label_06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(label_24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(button_column_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(label_21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(label_31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(label_26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(label_22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(label_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(button_column_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(label_25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(label_56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(icon_red))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(label_02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(612, 612, 612)
                .addComponent(tf_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(label_14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(icon_blue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(label_52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(button_column_5))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(label_36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(button_column_6))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(label_44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(label_53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(label_42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(button_column_2))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_player2))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(jButton8))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(label_33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_player2_ist_dran, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(label_23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(button_column_0))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(label_51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label_player1))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(label_34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label_player1_ist_dran, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(label_35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(label_my_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(label_32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(label_status)
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(label_45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(label_46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label_03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(label_55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(button_column_4))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(label_43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(label_54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(label_30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(label_24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(button_column_3))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(label_21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(label_50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(label_31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(label_20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(label_26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(label_22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(button_column_1))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(label_25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(label_56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icon_red, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(tf_chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(label_14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(icon_blue))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_connectActionPerformed
        new ConnenctWindow();
    }//GEN-LAST:event_menuItem_connectActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!Controller.socket.isConnected())
            return;
        String msg = Controller.myNick + "   " + MainGUI.tf_chat.getText();
        System.out.println("*******************" + Controller.myNick);
        Controller c = new Controller();
        c.sendMessage("CHAT:", msg);
        MainGUI.tf_chat.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tf_chatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_chatKeyPressed
        if(!Controller.socket.isConnected())
            return;
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            String msg = Controller.myNick.toString() + "   " + MainGUI.tf_chat.getText();
            Controller c = new Controller();
            c.sendMessage("CHAT:", msg);
            MainGUI.tf_chat.setText("");
        }    
    }//GEN-LAST:event_tf_chatKeyPressed

    private void button_column_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_column_0ActionPerformed
        if(!Controller.myNick.equals(Controller.currentPlayer))
            return;
        Controller c = new Controller();
        c.sendMessage("COLUMN:", "0");
    }//GEN-LAST:event_button_column_0ActionPerformed

    private void button_column_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_column_1ActionPerformed
        if(!Controller.myNick.equals(Controller.currentPlayer))
            return;
        Controller c = new Controller();
        c.sendMessage("COLUMN:", "1");
    }//GEN-LAST:event_button_column_1ActionPerformed

    private void button_column_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_column_2ActionPerformed
        if(!Controller.myNick.equals(Controller.currentPlayer))
            return;
        Controller c = new Controller();
        c.sendMessage("COLUMN:", "2");
    }//GEN-LAST:event_button_column_2ActionPerformed

    private void button_column_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_column_3ActionPerformed
        if(!Controller.myNick.equals(Controller.currentPlayer))
            return;
        Controller c = new Controller();
        c.sendMessage("COLUMN:", "3");
    }//GEN-LAST:event_button_column_3ActionPerformed

    private void button_column_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_column_4ActionPerformed
        if(!Controller.myNick.equals(Controller.currentPlayer))
            return;
        Controller c = new Controller();
        c.sendMessage("COLUMN:", "4");
    }//GEN-LAST:event_button_column_4ActionPerformed

    private void button_column_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_column_5ActionPerformed
        if(!Controller.myNick.equals(Controller.currentPlayer))
            return;
        Controller c = new Controller();
        c.sendMessage("COLUMN:", "5");
    }//GEN-LAST:event_button_column_5ActionPerformed

    private void button_column_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_column_6ActionPerformed
        if(!Controller.myNick.equals(Controller.currentPlayer))
            return;
        Controller c = new Controller();
        c.sendMessage("COLUMN:", "6");

    }//GEN-LAST:event_button_column_6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConnenctWindow cw = new ConnenctWindow();
        FileReader fr;
        try {
            fr = new FileReader("favouriten.txt");
            BufferedReader br = new BufferedReader(fr);
            String nick = br.readLine();
            String host = br.readLine();
            String port = br.readLine();
            cw.tf_nick.setText(nick);
            cw.tf_hostaddress.setText(host);
            cw.tf_port.setText(port);
        } catch (Exception ex) {
            System.out.println("Fehler beim 'join': \n" + ex.getMessage());
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Controller c = new Controller();
        c.disconnect();
        c.reset();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_column_0;
    private javax.swing.JButton button_column_1;
    private javax.swing.JButton button_column_2;
    private javax.swing.JButton button_column_3;
    private javax.swing.JButton button_column_4;
    private javax.swing.JButton button_column_5;
    private javax.swing.JButton button_column_6;
    private javax.swing.JLabel icon_blue;
    private javax.swing.JLabel icon_red;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel label_00;
    public static javax.swing.JLabel label_01;
    public static javax.swing.JLabel label_02;
    public static javax.swing.JLabel label_03;
    public static javax.swing.JLabel label_04;
    public static javax.swing.JLabel label_05;
    public static javax.swing.JLabel label_06;
    public static javax.swing.JLabel label_10;
    public static javax.swing.JLabel label_11;
    public static javax.swing.JLabel label_12;
    public static javax.swing.JLabel label_13;
    public static javax.swing.JLabel label_14;
    public static javax.swing.JLabel label_15;
    public static javax.swing.JLabel label_16;
    public static javax.swing.JLabel label_20;
    public static javax.swing.JLabel label_21;
    public static javax.swing.JLabel label_22;
    public static javax.swing.JLabel label_23;
    public static javax.swing.JLabel label_24;
    public static javax.swing.JLabel label_25;
    public static javax.swing.JLabel label_26;
    public static javax.swing.JLabel label_30;
    public static javax.swing.JLabel label_31;
    public static javax.swing.JLabel label_32;
    public static javax.swing.JLabel label_33;
    public static javax.swing.JLabel label_34;
    public static javax.swing.JLabel label_35;
    public static javax.swing.JLabel label_36;
    public static javax.swing.JLabel label_40;
    public static javax.swing.JLabel label_41;
    public static javax.swing.JLabel label_42;
    public static javax.swing.JLabel label_43;
    public static javax.swing.JLabel label_44;
    public static javax.swing.JLabel label_45;
    public static javax.swing.JLabel label_46;
    public static javax.swing.JLabel label_50;
    public static javax.swing.JLabel label_51;
    public static javax.swing.JLabel label_52;
    public static javax.swing.JLabel label_53;
    public static javax.swing.JLabel label_54;
    public static javax.swing.JLabel label_55;
    public static javax.swing.JLabel label_56;
    public static javax.swing.JLabel label_my_nick;
    public static javax.swing.JLabel label_player1;
    public static javax.swing.JLabel label_player1_ist_dran;
    public static javax.swing.JLabel label_player2;
    public static javax.swing.JLabel label_player2_ist_dran;
    public static javax.swing.JLabel label_status;
    private javax.swing.JMenuItem menuItem_connect;
    private javax.swing.JMenu menu_connect;
    public static javax.swing.JTextArea ta_chat;
    public static javax.swing.JTextField tf_chat;
    // End of variables declaration//GEN-END:variables
}
